### PR TITLE
Adding String and Array APIs, updating Object API

### PR DESCRIPTION
**Pull request by chasebish**
### Array (BoolArray, FloatArray, IntArray, StringArray)
I am aware this is long and there is a lot of code duplication. Earlier today I made this [Piazza post](https://piazza.com/class/k51bluky59n2jr?cid=331), asking for clarification on the issue, as well as speaking to Jan in person during office hours. It seems as if he wants the implementation to be four separate classes, one for each datatype. This is the data structure my group chose to implement for Assignment 1, and our updated version can be found [here](https://github.com/chasebish/cs4500_assignment1_part2).
I personally dislike this, but this is not a straightforward problem to solve since CwC has the issue of not having Generics. The alternative possibility is to create datatypes Boolean, Float, and Integer extending Object (similar to how Java does it), but it seems like creating 4 separate Array classes is simpler, albeit less scalable if we need to add more datatypes in the future. Additionally, Jan brought up the issue of memory, and making each of the datatypes into its own individual class would take up additional resources.

### String
I added this because it is needed for StringArray. I am making similar requests to all three of the APIs I have to implement in hopes to standardize a simple, easy to implement String API across all three.

### Object
The only change I made was adding `virtual ~Object() {}`. Again, I'm making similar requests to the other two APIs in hopes of standardization.

### Follow-up?
If you have any issues, I would like to resolve them as quick as possible. This API seems to be causing my group the most trouble so it would be mutually beneficial if we could get everything locked down as early as possible.

Chase

### CODE REVIEW

**Comment by chasebish** [comment]
tagging other people with this repo
@oriasm @jjones-99 @jsxtam

**Comment by jjones-99** [comment]
There might be a discussion on the memory requirements of having an `Integer` wrapper class vs. the primitive `int`, but on doing a little bit of research we don't think the cost of such wrappers is big enough to be worried about. (https://stackoverflow.com/questions/25229748/memory-overhead-of-wrapper-classes)

Personally, we believe that the cost of implementing four separate `Array`s and the associated code duplication and chance for error would be more worrisome.

We've seen in the `Queue` spec we're implementing and in our own spec for `Map` the use of wrapper classes (in those cases, they only need to support `String`s—which are already classes—so 'wrapper' might not be the most accurate word), and a central data structure storing `Object`s.

The derived classes (in this case, `IntArray`, `BoolArray`, `FloatArray`, and `StringArray`) would rely heavily on the Object`Array`, with the additions of casts to respective types upon retrieval.

The way we see it, the original Array that only supported Objects was acceptable for the requirements, but the downside is that the caller of these methods would have to repeatedly cast after each retrieval operation. By pulling those casts out into a `[Type]Array`, we make the code easier to use for the user. By deriving those `[Type]Array`s from an Object`Array`, we reduce the chance of errors in the code.

### Conclusion

We've been by-and-large implementing based on the spec we were given, and not what we want to turn the spec into—if that makes sense. So we'll give the final baton to the spec pair, but we think it would be more useful to still include the original `Array` class.

**Comment by chasebish** [comment]
I made a small gist with a simple implementation for Integer and then compared sizes, and Integer is 16 bits whereas int is only 4
[Gist](https://gist.github.com/chasebish/345d2c556c1408f2c36f6e8de0409f2a)

**Comment by jjones-99** [comment]
Oh yeah, that makes sense. There are three virtual methods, so Integer keeps a vtable and its size becomes `sizeof(int) + 3*sizeof(pointer)`, which in a 32-bit system becomes 16 bytes (int = 4 and pointer = 4). If there were no virtual methods, it'd still be 4.

### One Idea

We could get around that by making wrapper classes that don't use any virtual methods. For instance, instead of `Integer`, etc. extending `Object` they could extend a completely blank `ValueWrapper` class. That would mean the size wouldn't change but it would cut down on code duplication—however, it would mean we couldn't use dynamic dispatch for things like `equals()` and `hash()` (if we're using casting already, this might not be much of a blow).

### Our Final Thoughts

It's all down to the design choice, which is up to the spec pair. Memory vs. Speed vs. Code Duplication vs. Ease of Use vs. Scalability, etc. To do well in some areas we have to compromise in others.

We see the entire point of this assignment as following a spec pair's design choices. We may make suggestions, but ultimately it's their decision whether to incorporate them or not—we think this is a little exercise in what the real world might be like, working with specifications you don't have complete control over. But that discussion might be beyond the scale of this pull request.

**Comment by chasebish** [comment]
I removed some code duplication by creating an Array class to be inherited by the other Array classes. Additionally, I updated Object and String to match https://github.com/chasebish/cwc_object_string

**Comment by chasebish** [comment]
outdated

**Pull request closed without merging**
